import { Hf27LookDevController } from '../rendering/hf27-lookdev-controller';
import { resetHf27VisualProfile,serializeHf27VisualProfile } from '../rendering/hf27-visual-profile';

export const hf27LookDevEnabled=()=>new URLSearchParams(location.search).get('lookdev')==='1';
export function mountHf27LookDevPanel(game:unknown){
 if(!hf27LookDevEnabled())return ()=>{};
 const controller=new Hf27LookDevController(game);controller.startKeepAlive();
 const root=document.createElement('aside');root.id='hf27-lookdev';root.innerHTML='<header><strong>HF27 Visual LookDev</strong><button data-close>×</button></header><div data-body></div><footer><button data-reset>Reset</button><button data-copy>Copy JSON</button></footer>';
 const style=document.createElement('style');style.dataset.hf27Lookdev='1';style.textContent=`#hf27-lookdev{position:fixed;z-index:99999;right:12px;top:12px;width:min(370px,calc(100vw - 24px));max-height:calc(100vh - 24px);overflow:auto;background:rgba(13,24,31,.94);color:#e8f0f4;border:1px solid rgba(180,210,224,.32);border-radius:12px;box-shadow:0 18px 60px rgba(0,0,0,.45);font:12px/1.35 system-ui,sans-serif;backdrop-filter:blur(12px)}#hf27-lookdev header,#hf27-lookdev footer{position:sticky;z-index:2;display:flex;gap:8px;align-items:center;padding:10px;background:rgba(13,24,31,.96)}#hf27-lookdev header{top:0;justify-content:space-between;border-bottom:1px solid #314652}#hf27-lookdev footer{bottom:0;justify-content:flex-end;border-top:1px solid #314652}#hf27-lookdev [data-body]{padding:10px}#hf27-lookdev fieldset{border:1px solid #314652;border-radius:8px;margin:0 0 10px;padding:8px}#hf27-lookdev legend{color:#a8c8d8;padding:0 5px}#hf27-lookdev label{display:grid;grid-template-columns:128px 1fr 54px;gap:7px;align-items:center;margin:7px 0}#hf27-lookdev input[type=range]{width:100%}#hf27-lookdev input[type=color]{width:100%;height:26px;background:none;border:0}#hf27-lookdev output{text-align:right;font-variant-numeric:tabular-nums;color:#c7dce6}#hf27-lookdev button{border:1px solid #526a77;background:#233a46;color:#eef7fb;border-radius:6px;padding:5px 8px;cursor:pointer}`;document.head.appendChild(style);document.body.appendChild(root);
 const body=root.querySelector<HTMLElement>('[data-body]')!;
 const sections=[['Environment',[['Exposure','environment','exposure',.45,2.2,.01],['Environment','environment','environmentIntensity',0,3,.01],['Fog Density','environment','fogDensity',0,.004,.00001]]],['Lighting',[['Sun','lighting','sunIntensity',0,8,.02],['Hemisphere','lighting','hemisphereIntensity',0,1.5,.01],['Cool Fill','lighting','coolFillIntensity',0,2,.01],['Warm Rim','lighting','warmRimIntensity',0,2,.01],['Bounce','lighting','bounceIntensity',0,1,.01]]],['Post',[['Bloom','post','bloomStrength',0,.6,.005],['Bloom Radius','post','bloomRadius',0,1,.01],['Threshold','post','bloomThreshold',0,1.3,.01],['Grade','post','gradeStrength',0,1.5,.01],['Density','post','density',0,1.5,.01],['Chroma','post','chroma',0,1.5,.01],['Coral','post','coral',0,1.5,.01],['Teal','post','teal',0,1.5,.01],['Green Suppress','post','greenSuppress',0,1.5,.01]]] as const;
 const render=()=>{body.replaceChildren();const profile=controller.value;for(const [title,rows] of sections){const field=document.createElement('fieldset');field.innerHTML=`<legend>${title}</legend>`;for(const [label,group,key,min,max,step] of rows){const row=document.createElement('label'),value=(profile[group] as any)[key] as number;row.innerHTML=`<span>${label}</span><input type="range" min="${min}" max="${max}" step="${step}" value="${value}"><output>${value.toFixed(step<.001?5:2)}</output>`;const input=row.querySelector('input')!,out=row.querySelector('output')!;input.addEventListener('input',()=>{const next=controller.value;(next[group] as any)[key]=Number(input.value);out.textContent=Number(input.value).toFixed(step<.001?5:2);controller.apply(next);});field.appendChild(row);}body.appendChild(field);}const colors=document.createElement('fieldset');colors.innerHTML='<legend>Color</legend>';for(const [label,group,key] of [['Background','environment','background'],['Fog','environment','fogColor'],['Sun','lighting','sunColor'],['Sky','lighting','hemisphereSky'],['Ground','lighting','hemisphereGround'],['Cool Fill','lighting','coolFillColor'],['Warm Rim','lighting','warmRimColor']] as const){const row=document.createElement('label'),value=(profile[group] as any)[key] as string;row.innerHTML=`<span>${label}</span><input type="color" value="${value}"><output>${value}</output>`;const input=row.querySelector('input')!,out=row.querySelector('output')!;input.addEventListener('input',()=>{const next=controller.value;(next[group] as any)[key]=input.value;out.textContent=input.value;controller.apply(next);});colors.appendChild(row);}body.appendChild(colors);};render();
 root.querySelector('[data-close]')?.addEventListener('click',()=>{controller.dispose();root.remove();style.remove();});
 root.querySelector('[data-reset]')?.addEventListener('click',()=>{const next=resetHf27VisualProfile();controller.apply(next,false);render();});
 root.querySelector('[data-copy]')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(serializeHf27VisualProfile(controller.value));});
 return ()=>{controller.dispose();root.remove();style.remove();};
}
