import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import './verify-equipment-fit-modules.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8').replace(/^\uFEFF/,'');
const exists=p=>fs.existsSync(path.join(root,p));
const must=(ok,msg)=>{if(!ok)throw new Error(msg);console.log('PASS ',msg)};
const pkg=JSON.parse(read('package.json'));
const runtime=JSON.parse(read('public/assets/open/p022/runtime.json'));
const ui=read('src/client/ui/game-ui.ts');
const css=read('src/styles.css');
const game=read('src/client/core/game.ts');
const runtimeGuard=read('src/client/core/runtime-quality-guard.ts');
const renderer=read('src/client/world/world-renderer.ts');
const visualStyle=read('src/client/rendering/xianxia-visual-style.ts');
const curated=read('src/client/character/curated-equipment.ts');
const equipmentData=read('src/shared/data/equipment.ts');
const lootData=read('src/shared/data/loot-tables.ts');
const navigation=read('src/shared/domains/navigation.ts');
const persistence=read('server/persistence.ts');
const domainTests=read('tests/domains.test.ts');
const guiLauncher=read('QINGLAN_TEST_CENTER.py');
const worker=read('cloudflare/world-worker/src/index.js');
const wrangler=JSON.parse(read('cloudflare/world-worker/wrangler.jsonc'));
const networkPolicy=read('src/shared/network/network-policy.ts');
const panelRegistry=read('src/client/ui/panel-registry.ts');
const serverWorld=read('server/world.ts');
const serverIndex=read('server/index.ts');
const viteConfig=read('vite.config.ts');
const characterComposition=read('src/client/character/character-composition-runtime.ts');
const characterMorph=read('src/client/character/character-morph-runtime.ts');
const garmentMorph=read('src/client/character/garment-morph-runtime.ts');
const garmentAssetReport=JSON.parse(read('scripts/garment-morph-asset-report.json'));
const garmentBaker=read('scripts/bake-garment-morph-assets.mjs');
const garmentFitStandard=read('src/client/character/garment-fit-standard.ts');
const garmentModuleSync=read('scripts/sync-equipment-fit-modules.mjs');
const garmentModuleVerify=read('scripts/verify-equipment-fit-modules.mjs');
const editorEquipmentImport=read('server/equipment-import.ts');
const editorSource=read('src/editor/editor.ts');
const editorImportedRegistry=read('src/shared/data/editor-equipment.generated.ts');
const characterExpression=read('src/client/character/character-expression-runtime.ts');
const characterArchitecture=read('src/client/character/character-runtime-architecture.ts');
const vrmCharacterRuntime=read('src/client/character/vrm-character-runtime.ts');
const weaponAnimationProfiles=read('src/client/character/weapon-animation-profiles.ts');
const classAnimationSets=read('src/client/character/class-animation-sets.ts');
const combatAnimationResolver=read('src/client/character/combat-animation-resolver.ts');
const locomotionStyleProfiles=read('src/client/character/locomotion-style-profiles.ts');
const mixamoRetarget=read('src/client/character/mixamo-retarget.ts');
const weaponCombatMotion=read('src/client/character/weapon-combat-motion.ts');
const weaponGrip=read('src/client/character/weapon-grip.ts');
const monsterModel=read('src/client/character/monster-model.ts');
const monsterData=read('src/shared/data/monsters.ts');
must(pkg.version==='0.26.8','package release is 0.26.8');
must(runtime.release===`P${pkg.version}`&&runtime.enabled,'runtime release registry matches package');
must(Array.isArray(runtime.candidates)&&runtime.candidates.length===11,'11 selectable VRM characters remain registered');
for(const c of runtime.candidates)must(exists('public'+c.character),`character asset exists: ${c.id}`);
must(!exists('public/assets/user-world/xianxia_world.glb')&&!exists('src/assets/xianxia_world.glb')&&!exists('src/client/world/xianxia-uploaded-map-layer.ts')&&!exists('src/shared/data/xianxia-world-map.ts'),'HF26.5 physically removes the legacy uploaded world GLB and map implementation');
for(const f of ['linen_robe.glb','cloud_robe.glb','thunder_armor.glb','linen_boots.glb','cloud_boots.glb','thunder_boots.glb','iron_sword.glb','thunder_sword.glb','heaven_sword.glb'])must(exists('public/assets/equipment/'+f),`equipment asset exists: ${f}`);
must(exists('public/assets/user-equipment/ice-mythic-sword.glb'),'user-supplied ice mythic sword exists');
must(/id="mobile-controls"/.test(ui)&&/mobile-joystick/.test(ui),'mobile control surface remains present');
must(/setMobileMovement\(nx\/directionLength\*strength,ny\/directionLength\*strength/.test(ui),'mobile joystick forward/backward sign remains correct');
must(/--touch-target:48px/.test(css)&&/safe-area-inset-bottom/.test(css),'48px touch target and safe-area CSS remain present');
must(/this\.host\.getBoundingClientRect\(\)/.test(game)&&/visualViewport/.test(game),'renderer still uses mobile-safe viewport sizing');
must(/mobile-function-toggle/.test(ui)&&/mobile-menu-open/.test(css),'mobile HUD uses a collapsible function dock instead of a permanently expanded menu');
must(/equipment:\{id:'equipment',title:'人物'/.test(panelRegistry)&&/hotkeys:\['c'\]/.test(panelRegistry),'C-key character interface is labelled 人物 consistently');
must(/clampRenderScale/.test(game)&&/maxRenderTargetDimension/.test(game),'GPU framebuffer safety caps render-target scale');
must(/new T\.WebGLRenderTarget\(1,1/.test(game)&&/runtimePostProcessing==='off'/.test(game),'post-processing buffers stay tiny while the composer is bypassed');
must(/webglcontextlost/.test(game)&&/webglcontextrestored/.test(game)&&/lowerRuntimeQualityCap\('low','WebGL context loss'/.test(game),'WebGL context loss locks the runtime to a safe quality ceiling');
must(/classifyGraphicsHardware/.test(game)&&/clampGraphicsSettingsToCap/.test(game)&&/maxSamples/.test(game),'hardware quality classification consumes GPU and render-target capability');
must(/gameplaySeconds<15/.test(runtimeGuard)&&/threshold=34/.test(runtimeGuard)&&/threshold=27/.test(runtimeGuard)&&/!visible/.test(runtimeGuard)&&/document\.hidden/.test(game),'runtime FPS safety waits 15 s, ignores hidden tabs and enforces 34/27 FPS guards');
must(/inventory-actions-dock/.test(ui)&&/inventory-scroll/.test(ui)&&/previousScroll/.test(ui),'inventory actions are docked outside the independently scrolling item field');
must(/P0\.25\.9R6 Character panel UX/.test(css)&&/\.panel-equipment\{[\s\S]*overflow:hidden!important/.test(css)&&/equipment-inventory-grid[\s\S]*overflow-y:auto!important/.test(css),'character panel keeps header and 3D preview fixed while equipment library alone scrolls');
must(exists('tests/character-panel-r6.test.ts'),'character panel and uploaded ice sword regression test is packaged');
must(/P0\.25\.9R9 UI density/.test(css)&&/panel-dragged/.test(css)&&/makePanelDraggable/.test(ui)&&/headerRect\?\.bottom/.test(ui),'R9 compact character layout, draggable panels and panel-top item tooltip are present');
must(exists('tests/ui-layout-r9.test.ts'),'R9 responsive UI regression test is packaged');
must(/硬體不足/.test(ui)&&/settings-hardware-tier/.test(ui)&&/settings-max-quality/.test(ui),'settings expose hardware tier, maximum quality and disabled hardware labels');
must(/new HF265Terrain/.test(renderer)&&/new HF265QuaterniusNatureLayer/.test(renderer)&&/new HF265ArchitectureLayer/.test(renderer)&&/new HF265WaterLayer/.test(renderer)&&!/XianxiaUploadedMapLayer/.test(renderer),'HF26.5 six-layer Visual Reboot renderer is active without the old uploaded map');
must(/canonicalBoneName/.test(curated)&&/ice-mythic-sword\.glb/.test(curated)&&/'mythic-sword'/.test(curated),'curated equipment remap uses the uploaded ice sword for mythic-sword');
must(/'heaven-sword':'lightning'/.test(equipmentData),'heaven sword has explicit lightning combat VFX metadata');
must(/e\('kui-drum',4\)/.test(lootData)&&/e\('thunder-sword',1\),conditions:'firstKill'/.test(lootData),'Kui boss keeps exclusive drum and first-clear thunder sword rewards');
must(/SHARED_FINDER/.test(navigation)&&/valleyZoneReady/.test(navigation)&&/constructor\(\)\{ensureValleyZone\(\);\}/.test(navigation),'server navigation mesh is cached per process instead of rebuilt per GameWorld');
must(/gated showcase gear remains intentionally level-gated/.test(domainTests),'starter-bag regression test matches current gated-showcase design');

must(exists('QINGLAN_TEST_CENTER.py')&&exists('QINGLAN_TEST_CENTER.pyw'),'Python GUI launch/test center is packaged');
must(/npm-cli\.js/.test(guiLauncher)&&/npx-cli\.js/.test(guiLauncher)&&/_assert_direct\(command\)/.test(guiLauncher),'Python GUI runs Node/npm/Wrangler directly instead of delegating to batch launchers');
must(/本機啟動測試/.test(guiLauncher)&&/網路啟動測試/.test(guiLauncher)&&/完整發布預檢/.test(guiLauncher)&&/正式部署＋網路驗證/.test(guiLauncher),'Python GUI exposes local, network, preflight and deploy workflows in one interface');
must(/def network_test\(self, open_browser: bool\)/.test(guiLauncher)&&/_deployment_fingerprint/.test(guiLauncher)&&/_resolve_production_endpoint/.test(guiLauncher),'network startup test automatically resolves or deploys the Cloudflare endpoint');
must(!/請先填入網路網址/.test(guiLauncher)&&!/network_entry/.test(guiLauncher),'network workflow has no manual URL input requirement');
must(/_quiesce_for_dependency_mutation/.test(guiLauncher)&&/npm ci（EPERM 自動重試）/.test(guiLauncher)&&/taskkill\.exe/.test(guiLauncher),'Python GUI releases local Vite/backend/esbuild locks before npm ci');
must(/RETRYABLE_FILE_CODES/.test(persistence)&&/renameWithRetry/.test(persistence)&&/renameSyncWithRetry/.test(persistence)&&/tempSerial/.test(persistence),'persistence retries transient Windows rename locks with unique temp files');

must(exists('src/shared/network/network-policy.ts')&&/NETWORK_POLICY/.test(networkPolicy)&&/shouldSendSnapshot/.test(networkPolicy)&&/reconnectDelayMs/.test(networkPolicy),'network cadence, backpressure and reconnect behavior are centralized in one policy');
must(/NETWORK_SNAPSHOT_SCOPE/.test(serverIndex)&&/eventsAfter\(c\.lastEventId\)/.test(serverIndex)&&/shouldSendSnapshot/.test(serverIndex),'local server applies interest management, backpressure and per-client event cursors');
must(/SnapshotScope/.test(serverWorld)&&/distanceSquared/.test(serverWorld)&&/latestEventId/.test(serverWorld)&&/eventsAfter/.test(serverWorld),'world snapshot supports scoped network interest without changing authoritative full snapshots');
must(/NETWORK_SNAPSHOT_SCOPE/.test(worker)&&/eventsAfter\(state\.lastEventId\)/.test(worker)&&/shouldSendSnapshot/.test(worker),'Cloudflare Durable World uses the same network policy and event cursor model');
must(exists('src/client/ui/panel-registry.ts')&&/PANEL_DEFINITIONS/.test(panelRegistry)&&/equipment:\{id:'equipment',title:'人物'/.test(panelRegistry),'UI panel labels, titles and hotkeys are data-driven through the panel registry');
must(/panelForHotkey/.test(game)&&/PANEL_DEFINITIONS/.test(ui)&&/FUNCTION_PANEL_IDS/.test(ui),'game hotkeys and function menu consume the shared panel registry');
must(/vrm:\['@pixiv\/three-vrm'\]/.test(viteConfig)&&/pathfinding:\['three-pathfinding'\]/.test(viteConfig),'production build isolates Three, VRM and pathfinding vendor chunks for browser caching');
must(exists('tests/network-policy.test.ts')&&exists('tests/network-interest.test.ts')&&exists('tests/panel-registry.test.ts'),'network optimization and UI registry regression tests are packaged');
must(exists('tests/development-guard-r8.test.ts')&&exists('scripts/development-baseline.json'),'Development Guard regression test and SHA-256 baseline are packaged');
must(/PROJECT_RULES = \(/.test(guiLauncher)&&/class DevelopmentGuard/.test(guiLauncher)&&/CHANGE_IMPACT_RULES = \(/.test(guiLauncher),'Python GUI embeds executable development contracts instead of relying on chat notes');
must(/run_development_guard/.test(guiLauncher)&&/Development Guard/.test(guiLauncher)&&/Change Impact/.test(guiLauncher),'Development Guard executes before release workflows and reports change impact');

must(exists('scripts/verify-world-sync.mjs'),'WebSocket world-sync verifier is packaged');
must(exists('scripts/verify-package-integrity.mjs'),'package-integrity verifier is packaged');

must(!exists('START_GAME.bat')&&!exists('DEPLOY_CLOUDFLARE.bat')&&!exists('scripts/start-game.ps1')&&!exists('scripts/ensure-node-runtime.ps1'),'legacy BAT/PowerShell launchers are removed from the release package');
must(/PINNED_WRANGLER_VERSION\s*=\s*["']4\.135\.0["']/.test(guiLauncher)&&/deploy["']?,\s*["']--dry-run/.test(guiLauncher),'Python GUI pins Wrangler 4.135.0 and owns Worker dry-run');
must(/npm-cli\.js/.test(guiLauncher)&&/npx-cli\.js/.test(guiLauncher)&&/shell=False/.test(guiLauncher),'Python GUI owns direct dependency/build/test/deploy execution');
must(wrangler.assets?.directory==='../../dist'&&wrangler.assets?.not_found_handling==='single-page-application','Worker serves Vite dist with SPA fallback');
const first=wrangler.assets?.run_worker_first??[];must(['/api/*','/health','/socket'].every(x=>first.includes(x)),'API/health/socket execute Worker first');
must(/url\.pathname==='\/api\/release'/.test(worker)&&/url\.pathname==='\/api\/game-content'/.test(worker)&&/url\.pathname==='\/health'/.test(worker)&&/url\.pathname==='\/socket'/.test(worker),'Worker release/API, health and WebSocket routes exist');
must(exists('src/client/character/character-composition-runtime.ts')&&/CharacterCompositionRuntime/.test(characterComposition)&&/VrmCharacterRuntime/.test(characterComposition),'P0.26 character facade uses a stable TypeScript composition boundary');
must(/avatarAuthority:'vrm'/.test(characterArchitecture)&&/equipmentAuthority:'glb'/.test(characterArchitecture)&&/glb-mixamo/.test(characterArchitecture)&&/vrma/.test(characterArchitecture),'P0.26 architecture declares VRM avatar, GLB equipment and dual VRMA/GLB animation manifest');
must(/class CharacterMorphRuntime/.test(characterMorph)&&/private applyBody/.test(characterMorph)&&/private applyFace/.test(characterMorph)&&!/setCustomization\(_p:CharacterCustomization\)\{\}/.test(vrmCharacterRuntime),'P0.26 creator sliders drive live VRM body/face sculpting instead of an empty customization hook');
must(/CharacterExpressionRuntime/.test(characterExpression)&&/setValue\?\.\('blink'/.test(characterExpression),'P0.26 VRM expression runtime is separated from locomotion/combat animation');
must(exists('tests/character-architecture-p0260.test.ts'),'P0.26 character architecture regression test is packaged');
must(/NETWORK_RELEASE_PROPAGATION_TIMEOUT_SECONDS/.test(guiLauncher)&&/\/api\/release\?probe=/.test(guiLauncher)&&/Network Worker Release/.test(guiLauncher),'P0.26.2 deployment verification tolerates Worker/Durable Object rollout skew');
must(exists('tests/cloudflare-deployment-version-r262.test.ts'),'P0.26.2 Cloudflare rollout regression test is packaged');
must(exists('src/client/character/combat-animation-types.ts')&&exists('src/client/character/weapon-animation-profiles.ts')&&exists('src/client/character/class-animation-sets.ts')&&exists('src/client/character/combat-animation-resolver.ts'),'P0.26.3 combat animation schema/profile/resolver modules are packaged');
must(/actions:\{thrust:'SpearThrust',sweep:'SpearSweep',lunge:'SpearSkyPierce'\}/.test(weaponAnimationProfiles)&&/drawRelease:'BowShot'/.test(weaponAnimationProfiles)&&/kind:'bow-draw'/.test(weaponAnimationProfiles),'P0.26.3 spear thrust/sweep/lunge and bow Draw/Release live in weapon motion data');
must(/DEFAULT_CLASS_ANIMATION_SET_ID/.test(classAnimationSets)&&/weaponOverrides/.test(classAnimationSets)&&/resolveWeaponAnimationProfileForSet/.test(classAnimationSets),'P0.26.3 class Animation Set supports per-weapon overrides');
must(/resolveCombatMotionClip/.test(combatAnimationResolver)&&/animationProfileBindings/.test(combatAnimationResolver)&&!/profile==='(?:spear|staff|bow)'/.test(combatAnimationResolver)&&/resolveCombatMotionClip\(this\.profile/.test(vrmCharacterRuntime)&&!/if\(a\.skill==='spear-sweep'\)/.test(vrmCharacterRuntime),'P0.26.3 CharacterRuntime/resolver resolve combat motion through data instead of weapon/skill-specific branches');
must(/combatAnimationAssetOverride\(name\)/.test(characterArchitecture)&&/asset\?:AnimationAssetOverride/.test(read('src/client/character/combat-animation-types.ts')),'P0.26.3 individual actions can switch VRMA/GLB through motion data');
must(exists('tests/combat-animation-architecture-p0263.test.ts'),'P0.26.3 combat animation architecture regression test is packaged');


must(exists('src/client/character/locomotion-style-profiles.ts')&&/id:'heroic-grounded'/.test(locomotionStyleProfiles)&&/mixamorig:Hips/.test(locomotionStyleProfiles),'P0.26.4 grounded locomotion style profile is packaged and data-driven');
must(/styledSourceClip/.test(mixamoRetarget)&&/qinglanLocomotionStyle/.test(mixamoRetarget)&&/euler\.y\*=filter\.yawScale/.test(mixamoRetarget)&&/euler\.z\*=filter\.rollScale/.test(mixamoRetarget),'P0.26.4 locomotion style is applied before VRM retarget without replacing authored cadence');
must(/'heavenfall-bow':\{[^\n]*attach:'leftHand'/.test(curated)&&!/heavenfall-bow[^\n]*localRotation:\[0,-Math\.PI\/2,0\]/.test(curated)&&/primary:\{side:'left'/.test(weaponGrip)&&/proceduralMountRotation:\[0,0,0\]/.test(weaponGrip),'P0.26.8 bow is held by the left grip without a VRM-hand-local facing rotation');
must(/right hand travels back to the cheek\/string/.test(weaponCombatMotion)&&/\[\.20,1\.52,-\.03\]/.test(weaponCombatMotion)&&/\[\.70,1\.49,-\.22\]/.test(weaponCombatMotion),'P0.26.4 bow Draw/Anchor keeps string hand and elbow behind the bow');
must(/drawInEnd:\.36,anchorStart:\.46,releaseStart:\.64,releaseEnd:\.76/.test(weaponAnimationProfiles),'P0.26.4 bow Draw -> Anchor -> Release timing is data-driven');
must(exists('tests/locomotion-archery-p0264.test.ts'),'P0.26.4 locomotion/archery regression test is packaged');
must(/proceduralMountRotation\?:\[number,number,number\]/.test(weaponGrip),'P0.26.5 procedural weapon mount rotation is declared in the WeaponGripProfile TypeScript contract');
const equipmentDomain=read('src/shared/domains/equipment.ts');
const locomotionData=read('src/shared/data/locomotion.ts');
const appearance=read('src/client/character/appearance.ts');
must(/TWO_HANDED_WEAPON_PROFILES[\s\S]*greatsword[\s\S]*dual[\s\S]*spear[\s\S]*staff[\s\S]*bow/.test(equipmentDomain)&&/base\.slot==='offhand'&&mainhandBlocksOffhand/.test(equipmentDomain)&&/repairIllegalHandLoadout/.test(equipmentDomain),'P0.26.6 two-hand weapons authoritatively exclude offhand equipment and legacy saves are repaired');
must(/PLAYER_WALK_RUN_BLEND_HALF_WIDTH=\.72/.test(locomotionData)&&/PLAYER_AUTHORED_LOCOMOTION\.walk\.speed\+PLAYER_AUTHORED_LOCOMOTION\.run\.speed/.test(locomotionData)&&/PLAYER_WALK_RUN_BLEND_HALF_WIDTH/.test(vrmCharacterRuntime),'P0.26.6 gameplay travel speed and authored gait selection are separated');
must(/leftReach/.test(vrmCharacterRuntime)&&/rightReach/.test(vrmCharacterRuntime)&&/bowAnchor/.test(vrmCharacterRuntime)&&/for\(const child of g\.children\)child\.position\.x-=gripX/.test(appearance),'P0.26.6 bow pose uses avatar-proportional arm reach and procedural bow pivot is centered on the physical grip');
must(/staff:\{[\s\S]*secondary:\{side:'left',offset:\[0,\.40,0\]/.test(weaponGrip),'P0.26.6 staff has a real bounded support-hand grip instead of a free shield hand');
must(exists('tests/equipment-two-hand-p0266.test.ts')&&exists('tests/locomotion-gait-p0266.test.ts'),'P0.26.6 two-hand and gait regression tests are packaged');
const renderedMotion=read('src/client/character/rendered-motion.ts');
must(/renderedGroundSpeed/.test(renderedMotion)&&/Math\.hypot\(dx,dz\)\/sample\.dt/.test(renderedMotion)&&/authoritativeSpeed\*1\.12\+\.08/.test(renderedMotion),'P0.26.7 foot cadence is driven by rendered X/Z travel and reconciliation spikes are capped');
must(/predictAge=Math\.min\(\.32/.test(game)&&/const visualSpeed=renderedGroundSpeed/.test(game)&&(/c\.update\(dt,this\.time,self,visualSpeed\)/.test(game)||/c\.update\(hitStopActive\?0:dt,this\.time,self,hitStopActive\?0:visualSpeed\)/.test(game)),'P0.26.7 local render prediction remains continuous and animation receives rendered movement speed');
must(exists('tests/rendered-locomotion-p0267.test.ts'),'P0.26.7 rendered-locomotion regression test is packaged');
must(/this\.profile==='bow'&&this\.hasMainhand&&side==='left'/.test(vrmCharacterRuntime)&&/makeBasis\(this\.bowForward,this\.bowUp,this\.palmNormal\)/.test(vrmCharacterRuntime),'P0.26.8 bow mount uses character/world facing instead of avatar-specific palm axes');
must(/spear:\{[\s\S]*combatIk:\.82[\s\S]*combatCap:\.86/.test(weaponGrip)&&/staff:\{[\s\S]*combatIk:\.76[\s\S]*combatCap:\.80/.test(weaponGrip)&&/secondary\.combatCap/.test(vrmCharacterRuntime),'P0.26.8 spear/staff attacks keep a strong physical second-hand shaft contact');
must(exists('tests/two-hand-bow-facing-p0268.test.ts'),'P0.26.8 two-hand/bow-facing regression test is packaged');
must(/visualHeightRatio:2\.20/.test(monsterData)&&/measureHumanoidSkeletonFrame/.test(monsterModel)&&/BOSS_MIN_HEIGHT_RATIO=2/.test(monsterModel)&&/BOSS_MAX_HEIGHT_RATIO=3/.test(monsterModel),'P0.26.8 HF2 Golden Queen uses skeleton height with a 2x-3x authored boss clamp');
must(exists('tests/golden-queen-scale-hf2.test.ts'),'P0.26.8 HF2 Golden Queen scale regression test is packaged');
must(exists('src/client/character/garment-morph-runtime.ts')&&/class GarmentMorphRuntime/.test(garmentMorph)&&/garmentMorphWeight/.test(garmentMorph)&&/registerGarment/.test(vrmCharacterRuntime)&&/updateMorphTargets\(\)/.test(curated),'P0.26.8 HF4 garments share avatar skeleton and synchronize body-shape Morph Targets by name');
must(/bodyMass/.test(characterMorph)&&/muscle/.test(characterMorph)&&/multiplyBoneScale/.test(characterMorph),'P0.26.8 HF4 bodyMass and muscle creator controls affect the avatar body before garment morph sync');
must(exists('tests/garment-morph-hf4.test.ts'),'P0.26.8 HF4 garment morph regression test is packaged');
must(garmentAssetReport.bakeVersion==='HF5'&&garmentAssetReport.totalAssets===13&&garmentAssetReport.totalGeneratedMorphBindings>=900&&/inverseBindMatrices/.test(garmentBaker)&&/qinglanGarmentMorphBakeVersion/.test(garmentBaker),'P0.26.8 HF5 all 13 skinned garments contain reproducible bone-weight-driven residual Body Morph assets');
must(exists('scripts/verify-garment-morph-assets.mjs')&&exists('tests/garment-morph-assets-hf5.test.ts'),'P0.26.8 HF5 garment asset verifier and regression test are packaged');
must(/bindPoseTransferred/.test(curated)&&/transferBindPoint/.test(curated)&&/curatedSkinTarget/.test(curated)&&/skinTarget=this\.equipmentSkinTarget\(\)/.test(vrmCharacterRuntime),'P0.26.8 HF6 skinned garments transfer source bind pose into the avatar bind pose before Morph sync');
must(/authoritative translation follows the already-validated[\s\S]*navigation direction/.test(serverWorld)&&/pursuitFallback/.test(serverWorld)&&/finalCombatNode/.test(serverWorld),'P0.26.8 HF6 combat pursuit follows nav vectors continuously without facing-angle collision stalls');
must(exists('tests/garment-bind-pursuit-hf6.test.ts'),'P0.26.8 HF6 garment bind-pose / pursuit regression test is packaged');

must(/FIT_REQUIRED_SLOTS/.test(curated)&&/generatedFitDefinition/.test(curated)&&/generated-skinned/.test(curated)&&/FIT_TEMPLATE_BY_SLOT/.test(curated)&&/fitPipeline='HF8'/.test(vrmCharacterRuntime),'P0.26.8 HF8 all body-worn equipment resolves through authored/template/generated/auto-module skinned fit pipeline');
must(/generatedResidualMorphs/.test(curated)&&/sharedAvatarSkeleton/.test(curated)&&/instantiateGeneratedSkinnedWearable/.test(curated),'P0.26.8 HF7 generated shoulders/gloves/capes remain skeleton-bound and Morph-capable');
must(/BODY_FIT_SLOTS/.test(garmentFitStandard)&&/GARMENT_MORPHS_BY_SLOT/.test(garmentFitStandard)&&/AUTO_RIG_BONES_BY_SLOT/.test(garmentFitStandard),'P0.26.8 HF8 central fit standard governs future body-worn equipment');
must(/automaticGlbFitDefinition/.test(curated)&&/autoRigRigidWearable/.test(curated)&&/ensureStandardMorphTargets/.test(curated)&&/applyGarmentClearanceMorph/.test(curated)&&/HF8_CLEARANCE_MORPH/.test(curated),'P0.26.8 HF8 new GLB modules auto-rebind/auto-rig, complete semantic Morphs and receive clearance correction');
must(/equipment\/modules/.test(garmentModuleSync)&&/rigid-auto-rig/.test(garmentModuleVerify)&&/skinned-rebind/.test(garmentModuleVerify),'P0.26.8 HF8 module scanner and Fit Manifest verifier are packaged');
must(exists('tests/all-garment-fit-hf7.test.ts')&&exists('tests/garment-auto-fit-hf8.test.ts'),'P0.26.8 HF8 garment coverage and automatic-module regressions are packaged');
must(/api\/editor\/import-equipment/.test(serverIndex)&&/editor-import-glb/.test(editorSource)&&/analyzeEquipmentGlb/.test(editorEquipmentImport)&&/createImportedEquipmentRecords/.test(editorEquipmentImport),'P0.26.8 HF9 world editor one-click GLB import analyzes assets and creates equipment metadata automatically');
must(/syncEditorEquipmentRegistry/.test(editorEquipmentImport)&&/EDITOR_IMPORTED_ITEMS/.test(equipmentData)&&/EDITOR_IMPORTED_APPEARANCES/.test(equipmentData)&&/HF9 local editor import pipeline/.test(editorImportedRegistry),'P0.26.8 HF9 imported equipment is materialized into generated source data for restart/build/deploy');
must(/rigid-attachment/.test(editorEquipmentImport)&&/skinned-rebind/.test(editorEquipmentImport)&&/rigid-auto-rig/.test(editorEquipmentImport)&&/autoOrientWeapon/.test(curated),'P0.26.8 HF9 imported body garments and rigid equipment automatically select the correct runtime fit/attachment strategy');
must(exists('scripts/verify-editor-equipment-import.mjs')&&exists('tests/editor-equipment-import-hf9.test.ts'),'P0.26.8 HF9 editor import verifier and regression test are packaged');

must(/!n\.startsWith\('right'\)/.test(read('src/client/character/bone-names.ts'))&&/RightUpperArm/.test(read('src/client/character/bone-names.ts')),'P0.26.8 HF10 right-side humanoid bones survive canonical prefix normalization');
must(/body target=/.test(vrmCharacterRuntime)&&/face\|hair\|eye/.test(vrmCharacterRuntime)&&/fittedGarmentRenderable/.test(vrmCharacterRuntime)&&/forceGarmentVisible/.test(vrmCharacterRuntime),'P0.26.8 HF10 garment fit chooses a body skin and hard-gates visible fitted meshes before masking the base outfit');
must(exists('tests/garment-visibility-hf10.test.ts'),'P0.26.8 HF10 garment visibility regression test is packaged');
must(exists('src/shared/data/skill-vfx-profiles.ts')&&/SKILL_VFX_PROFILES/.test(read('src/shared/data/skill-vfx-profiles.ts'))&&/fire-burst/.test(read('src/shared/data/skill-vfx-profiles.ts'))&&/ice-spikes/.test(read('src/shared/data/skill-vfx-profiles.ts'))&&/blizzard/.test(read('src/shared/data/skill-vfx-profiles.ts')),'P0.26.8 HF11 fireball, ice-spike and blizzard use data-driven spell VFX profiles');
must(/projectilePool/.test(read('src/client/rendering/xianxia-skill-fx.ts'))&&/updateProjectiles/.test(read('src/client/rendering/xianxia-skill-fx.ts'))&&/updateFields/.test(read('src/client/rendering/xianxia-skill-fx.ts'))&&/spellParticleCursor/.test(read('src/client/rendering/xianxia-skill-fx.ts')),'P0.26.8 HF11 spell projectiles, persistent fields and particles use bounded runtime pools');
must(/staff:\['basic','fire-orb','ice-spike','blizzard','dash'\]/.test(read('src/shared/combat/weapon-skills.ts'))&&/'ice-spike':'StaffSeal'/.test(read('src/client/character/weapon-animation-profiles.ts'))&&/'blizzard':'StaffSkyCall'/.test(read('src/client/character/weapon-animation-profiles.ts'))&&exists('tests/skill-vfx-hf11.test.ts'),'P0.26.8 HF11 staff hotbar exposes fireball, ice-spike and blizzard with distinct cast motions and regression coverage');
must(/castAt\?: number/.test(read('src/shared/types.ts'))&&/impactAt\?: number/.test(read('src/shared/types.ts'))&&/castAt:p\.attack\.started/.test(serverWorld)&&/impactAt:p\.attack\.hitAt/.test(serverWorld),'P0.26.8 HF12 authoritative cast/impact timestamps keep VFX aligned under network latency');
must(/telegraph\?:SpellTelegraphVfx/.test(read('src/shared/data/skill-vfx-profiles.ts'))&&/startTelegraph/.test(read('src/client/rendering/xianxia-skill-fx.ts'))&&/updateTelegraphs/.test(read('src/client/rendering/xianxia-skill-fx.ts')),'P0.26.8 HF12 profiled spells expose readable player-side target telegraphs');
must(/projectileBudget\(\)/.test(read('src/client/rendering/xianxia-skill-fx.ts'))&&/fieldBudget\(\)/.test(read('src/client/rendering/xianxia-skill-fx.ts'))&&/telegraphBudget\(\)/.test(read('src/client/rendering/xianxia-skill-fx.ts'))&&/scratchDirection/.test(read('src/client/rendering/xianxia-skill-fx.ts')),'P0.26.8 HF12 spell VFX budgets cap simultaneous expensive effects and avoid hot-loop vector allocation');
must(/skill\.multiplier-1/.test(game)&&/criticalScale=event\.critical/.test(game)&&exists('tests/skill-vfx-hf12.test.ts'),'P0.26.8 HF12 impact feedback scales camera/audio presentation with skill power and critical hits');
must(exists('src/shared/data/monster-telegraph-profiles.ts')&&/PATH_SKILLS/.test(read('src/shared/data/monster-telegraph-profiles.ts'))&&/CONE_SKILLS/.test(read('src/shared/data/monster-telegraph-profiles.ts')),'P0.26.8 HF13 enemy telegraphs classify charge/dash paths and breath/feather cones without replacing the authoritative endpoint radius');
must(/createTelegraph\(m:Monster\)/.test(read('src/client/rendering/effects.ts'))&&/new T\.PlaneGeometry/.test(read('src/client/rendering/effects.ts'))&&/new T\.ShapeGeometry/.test(read('src/client/rendering/effects.ts')),'P0.26.8 HF13 monster warning renderer adds directional path/cone guides while retaining endpoint AoE circles');
must(/WORLD_STATUS_EFFECTS/.test(read('src/client/rendering/effects.ts'))&&/syncStatuses/.test(read('src/client/rendering/effects.ts'))&&/statusVisuals/.test(read('src/client/rendering/effects.ts'))&&/target\.effects/.test(read('src/client/ui/game-ui.ts')),'P0.26.8 HF13 server-authoritative poison/burn/bleed/slow/freeze/shock states are readable in-world and on the target frame');
must(/scheduleLocalHitStop/.test(game)&&/localHitStopUntil/.test(game)&&/impactFrozen/.test(game)&&/\.075/.test(game)&&exists('tests/combat-readability-hf13.test.ts'),'P0.26.8 HF13 bounded local-only hit-stop adds impact weight without pausing server/network time');
must(/fitStrategy\?:'preserve-authored'\|'bind-transfer'\|'anatomical-transfer'/.test(curated)&&/remapSkinPreserveAuthored/.test(curated)&&/HF14-compat/.test(curated),'P0.26.8 HF14 compatibility rebind remains available while imported assets retain bind-pose transfer');
must(/remapSkinAnatomical/.test(curated)&&/ANATOMICAL_CHILD/.test(curated)&&/HF15-anatomical/.test(curated)&&exists('tests/garment-anatomical-fit-hf15.test.ts'),'P0.26.8 HF15 project-authored garments use anatomy-frame rest-pose transfer for real body fit');
must(/'primordial-god-crown'[\s\S]*localRotation:\[0,Math\.PI,0\]/.test(curated),'P0.26.8 HF14 primordial god crown receives an explicit 180-degree front/back correction');
must(/refreshNearestAutoTarget/.test(serverWorld)&&/p\.target=nearest\.id;p\.path=\[\];p\.pursuitNextAt=this\.time/.test(serverWorld)&&/mobileBasicAttack\(\).*skill:'basic'\}/.test(game),'P0.26.8 HF14 auto combat continuously owns the nearest living monster and invalidates stale pursuit paths');
must(exists('src/shared/identity/character-name.ts')&&/CHARACTER_NAME_TAKEN/.test(serverIndex)&&/characterNameKey/.test(serverIndex)&&/mode==='create'/.test(serverIndex),'P0.26.8 HF17 server owns character-name validation and globally unique creation');
must(/mode==='create'/.test(worker)&&/CHARACTER_NAME_TAKEN/.test(worker)&&/characterNameKey/.test(worker),'P0.26.8 HF17 Cloudflare Durable World enforces the same unique-name rule');
must(/connectCreate/.test(read('src/client/networking/connection.ts'))&&/connectCharacter/.test(read('src/client/networking/connection.ts'))&&/qinglan-characters-v1/.test(read('src/client/identity/local-characters.ts')),'P0.26.8 HF17 client separates create from resume and stores multiple local character sessions');
must(/character-roster/.test(read('src/client/ui/game-ui.ts'))&&/completeCharacterLogin/.test(read('src/client/ui/game-ui.ts'))&&exists('tests/character-login-hf17.test.ts'),'P0.26.8 HF17 login UI waits for authoritative snapshot and ships identity regression coverage');
must(/autofocus/.test(read('src/client/ui/game-ui.ts'))&&/input\.readOnly=busy/.test(read('src/client/ui/game-ui.ts'))&&/NETWORK_TRANSIENT/.test(game)&&/this\.typing\(e\)/.test(read('src/client/input/game-input-controller.ts'))&&exists('tests/character-login-input-hf17.test.ts'),'P0.26.8 HF17.2 desktop character-name input remains focusable and cannot be permanently locked by transient network failure');
must(/toMatch\(\/enterkeyhint=/.test(read('tests/character-login-input-hf17.test.ts'))&&/Decode the common/.test(read('QINGLAN_TEST_CENTER.py'))&&!/toContain\('enterkeyhint=\\\"done/.test(read('tests/character-login-input-hf17.test.ts')),'P0.26.8 HF17.3 semantic guard handles escaped source assertions without stale-string false positives');
must(/activeLocalCharacterToken/.test(read('src/client/ui/game-ui.ts'))&&/qinglan-active-character-v1/.test(read('src/client/identity/local-characters.ts'))&&/resumeStaleMs:12000/.test(read('src/shared/network/network-policy.ts'))&&/e\.code===4009/.test(read('src/client/networking/connection.ts'))&&exists('tests/mobile-session-continuity-hf174.test.ts'),'P0.26.8 HF17.4 mobile session continuity preserves per-device character identity and reconnects after lifecycle suspension');
must(/XIANXIA_GRADIENTS/.test(visualStyle)&&/MeshStandardMaterial/.test(visualStyle)&&/applyXianxiaWorldArtDirection/.test(visualStyle)&&/terrain-water/.test(visualStyle),'P0.26.8 HF18 commercial xianxia palette recolors world surfaces and separates semantic PBR materials');
must(/SRGBColorSpace/.test(game)&&/ACESFilmicToneMapping/.test(game)&&/PCFSoftShadowMap/.test(game)&&/UnrealBloomPass/.test(game)&&/hardware preflight/.test(game),'P0.26.8 HF18 renderer keeps sRGB + ACES + soft shadows + adaptive bloom behind pre-load hardware gating');
must(/standardizeXianxiaMaterial/.test(read('src/client/character/vroid-runtime.ts'))&&/standardizeXianxiaMaterial/.test(curated)&&/standardizeXianxiaMeshMaterials/.test(read('src/client/assets/open-monster-assets.ts')),'P0.26.8 HF18 avatars, equipment and imported monsters use the common MeshStandardMaterial art-direction bridge');
must(exists('tests/visual-style-hf18.test.ts'),'P0.26.8 HF18 visual-style regression coverage is packaged');
const hf265Layout=read('src/shared/data/hf265-world-layout.ts');
const hf265World=read('src/client/world/world-renderer.ts');
const hf265Nature=read('src/client/world/hf265-quaternius-nature-layer.ts');
const hf265Registry=read('src/client/assets/quaternius-asset-registry.ts');
const hf265Equipment=read('src/client/rendering/hf265-equipment-art-direction.ts');
const hf22Pipeline=read('src/client/rendering/cinematic-rendering-pipeline.ts');
must(/HF265_NATURE_PLACEMENTS/.test(hf265Layout)&&/HF265_COLLIDERS/.test(hf265Layout)&&/hf265TerrainHeight/.test(hf265Layout)&&/hf265AreaClear/.test(hf265Layout),'P0.26.8 HF26.5 shared world-layout owns placement, height and collision authority');
must(/HF265Terrain/.test(hf265World)&&/HF265QuaterniusNatureLayer/.test(hf265World)&&/HF265ArchitectureLayer/.test(hf265World)&&/HF265WaterLayer/.test(hf265World)&&/HF265Atmosphere/.test(hf265World)&&/HF265HorizonMountains/.test(hf265World),'P0.26.8 HF26.5 Visual Reboot composes all six new world layers');
must(/raw\.githubusercontent\.com/.test(hf265Registry)&&/CC0-1\.0/.test(hf265Registry)&&/quaterniusNatureUrl/.test(hf265Nature)&&/InstancedMesh/.test(hf265Nature),'P0.26.8 HF26.5 uses verified Quaternius CC0 nature assets with instanced rendering');
must(/applyHF265EquipmentArtDirection/.test(curated)&&/mist-blue \/ antique-gold \/ jade \/ coral/.test(hf265Equipment)&&/metalness=.72/.test(hf265Equipment),'P0.26.8 HF26.5 equipment receives unified mist-blue, antique-gold, jade and coral art direction');
must(/float ta=1\.42\*a-\.16\*b\+\.003/.test(hf22Pipeline)&&/float tb=-\.08\*a\+1\.36\*b-\.004/.test(hf22Pipeline)&&!/2\.21279016/.test(hf22Pipeline),'P0.26.8 HF26.5 softens Oklab grading to avoid neon/cheap chroma');
must(/SSAOPass/.test(game)&&/toneMappingExposure=pp==='cinematic'\?1\.00/.test(game)&&/bloomPass\.strength=pp==='cinematic'\?\.14/.test(game),'P0.26.8 HF26.5 keeps ACES/contact depth with restrained bloom');
must(/hf265AreaClear/.test(navigation)&&!/XIANXIA_MAP/.test(navigation),'P0.26.8 HF26.5 navigation is generated from the new shared world instead of legacy GLB forest data');
must(exists('scripts/fetch-quaternius-hf265.mjs')&&exists('public/assets/quaternius/nature/README_LICENSE.txt')&&exists('tests/visual-reboot-hf265.test.ts')&&exists('README_P0.26.8_HF26.5_Visual_Reboot.txt'),'P0.26.8 HF26.5 vendor workflow, license note, regression gate and release notes are packaged');
const hf26Profile=JSON.parse(read('public/assets/reference-20260925/reference-style-profile.json'));
must(hf26Profile.luminance?.median===0.3334&&hf26Profile.palette?.[0]?.hex==='#1D4459','P0.26.8 HF26 keeps the measured reference-image palette/luminance as calibration evidence');
console.log('CURRENT PROJECT VERIFICATION: PASS');
