import './verify-r15.mjs';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8').replace(/^\uFEFF/,'');
const pass=(ok,msg)=>{if(!ok)throw new Error(msg);console.log('PASS ',msg)};
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');
const runtime=read('src/client/character/vrm-character-runtime.ts');
const retarget=read('src/client/character/mixamo-retarget.ts');
const pkg=JSON.parse(read('package.json'));
const gui=read('QINGLAN_TEST_CENTER.py');
const locomotion=read('src/shared/data/locomotion.ts');
const world=read('server/world.ts');
const queen=read('src/client/character/golden-queen-animator.ts');
const grip=read('src/client/character/weapon-grip.ts');
const curated=read('src/client/character/curated-equipment.ts');
const ready=read('src/client/character/action-rpg-weapon-layer.ts');
const bowDraw=read('src/client/character/bow-draw-hand.ts');
const animationProfiles=read('src/client/character/weapon-animation-profiles.ts');
pass(/type LocomotionLayer='full'\|'weapon'/.test(runtime)&&/layeredLocomotionActions/.test(runtime)&&/QinglanWeaponBody_/.test(runtime),'R17 creates separate full-body and weapon/body locomotion layers');
const mask=runtime.match(/const BODY_LOCOMOTION_SEMANTICS=\[([\s\S]*?)\] as const;/m)?.[1]??'';
pass(/leftUpperLeg/.test(mask)&&/rightFoot/.test(mask)&&/upperChest/.test(mask)&&!/UpperArm|LowerArm|Hand|Shoulder|Thumb|Index|Middle|Ring|Little/.test(mask),'weapon locomotion mask keeps body/legs but excludes weapon-arm and finger tracks');
pass(/private weaponLayerBlend=0/.test(runtime)&&/weaponTarget-this\.weaponLayerBlend/.test(runtime)&&/this\.locomotionLayer='full'/.test(runtime)&&/walkFull\.setEffectiveWeight\(walkWeight\*weightScale\)/.test(runtime)&&/layeredLocomotionActions\.values\(\)\)action\.setEffectiveWeight\(0\)/.test(runtime),'R26 equipment preserves full authored locomotion and does not replace moving arms with body-only weapon locomotion');
const upper=runtime.match(/const WEAPON_UPPER_BASE_SEMANTICS=\[([\s\S]*?)\] as const;/m)?.[1]??'';
pass(/leftShoulder/.test(upper)&&/rightHand/.test(upper)&&!/UpperLeg|Foot|hips/.test(upper)&&/QinglanWeaponUpperBase_Idle/.test(runtime),'R18 supplies an authored Idle upper-body baseline instead of T-pose fallback');
pass(/weaponUpperBaseAction\?\.setEffectiveWeight\(0\)/.test(runtime)&&/resolveWeaponAnimationProfile\(this\.profile,this\.classAnimationSetId\)\.stance\.ready/.test(runtime)&&/const stationary=1-T\.MathUtils\.smoothstep\(speed,\.10,\.90\)/.test(runtime),'R26 keeps full locomotion authoritative and applies only a small stationary additive weapon-ready layer');
pass(/createActionRpgReadyClip/.test(runtime)&&/weaponReadyActions/.test(runtime)&&/makeClipAdditive/.test(ready)&&/MAX_ANGLE_DEG/.test(ready)&&!/createClassicMmoGuardClip|createClassicMmoBasicAttackClip|BASIC_ATTACK_ARM_IK|applyWeaponCombatChoreography|applyPrimaryWeaponOrientation/.test(runtime),'R26 uses clamped rig-derived additive ready poses and authored attack clips; synthetic/world-space primary-arm posing is removed');
pass(/animationMixer\?\.update\(dt\)[\s\S]*updateVroid\(this\.handle,dt\)[\s\S]*applySecondaryHandContactIK\(\)[\s\S]*syncHandMounts\(\)/.test(runtime),'R26/P0.26.8 final pose order is locomotion/authored attack -> additive ready -> VRM propagation -> bounded physical support contact -> finger grip');
pass(/PLAYER_WALK_RUN_SWITCH-PLAYER_WALK_RUN_BLEND_HALF_WIDTH/.test(runtime)&&/PLAYER_WALK_RUN_SWITCH\+PLAYER_WALK_RUN_BLEND_HALF_WIDTH/.test(runtime)&&/syncLoopPhase/.test(runtime),'Walk/Run retain authored-speed gait crossfade and transition phase handoff');
pass(/locomotionStrideLength/.test(runtime)&&/blendedStride=T\.MathUtils\.lerp\(walkStride,runStride,runBlend\)/.test(runtime)&&/phaseHz=this\.cadenceSpeed/.test(runtime)&&/walkFull\.setEffectiveTimeScale\(walkClip\?phaseHz\*walkClip\.duration:0\)/.test(runtime)&&/runFull\.setEffectiveTimeScale\(runClip\?phaseHz\*runClip\.duration:0\)/.test(runtime),'R21 foot cadence uses target-proportioned stride length and one normalized phase velocity');
pass(/this\.setLocomotion\(backgroundSpeed,1-this\.activeOneShotBlend,false\)/.test(runtime),'all one-shots fade against full authored locomotion without forcing weapon-safe body-only arms');
pass(/premultiply\(parentRestWorld\)\.multiply\(restWorldInv\)/.test(retarget)&&/if\(vrm0\)\{q\.x=-q\.x;q\.z=-q\.z;\}/.test(retarget)&&/retargetVrmNormalizedClip/.test(retarget),'R21 follows official three-vrm normalized-bone Mixamo retarget including VRM0 axis conversion');
pass(/buildHipsPositionTrack/.test(retarget)&&/worldBob\.set\(0,T\.MathUtils\.clamp\(delta\.y,-\.10,\.10\),0\)/.test(retarget),'R21 keeps gameplay root travel outside Hips while retaining bounded vertical pelvis bob');
pass(/visualBasePosition/.test(runtime)&&/visualBaseQuaternion/.test(runtime)&&/enforceVisualRootInvariant/.test(runtime)&&/this\.root\.position\.x=0;this\.root\.position\.z=0;this\.root\.quaternion\.identity\(\)/.test(runtime),'R20 separates gameplay root from visual VRM root and reasserts the grounded transform');
const resolveBlock=runtime.match(/private resolveAnimation\([\s\S]*?\n  \}\n  playPickup/m)?.[0]??'';
const priority=[resolveBlock.indexOf('if(actor.hp<=0)'),resolveBlock.indexOf('if(actor.staggerUntil>time&&hitAge>=0)'),resolveBlock.indexOf('const authoritative=actor.attack'),resolveBlock.indexOf('if(!actor.flight&&jumpAge>=0&&jumpAge<jumpDuration)'),resolveBlock.lastIndexOf('if(this.pickup)')];
pass(priority.every(x=>x>=0)&&priority.every((x,i)=>i===0||priority[i-1]<x),'R19 motion priority is Death > Hit > Attack > Jump > Pickup');
pass(/motionEnvelope\(/.test(runtime)&&/staggerDuration=Math\.max\(\.12,actor\.staggerUntil-actor\.hitAt\)/.test(runtime)&&/oneShot\('Hit',[\s\S]*?,phase,speed,weight\)/.test(runtime),'R19 Hit/Jump/Pickup/Death use blended one-shot transitions and authoritative Hit timing');
pass(/reconciledCombatVisualPhase/.test(runtime)&&/combatPhaseCorrection=T\.MathUtils\.clamp\(this\.activeCombatPhase-raw,-\.16,\.16\)/.test(runtime)&&/Math\.exp\(-age\*18\)/.test(runtime),'R19 predicted attacks reconcile into server-authoritative phase without a confirmation snap');
pass(/nonCombatArmOwnership/.test(runtime)&&/secondary\.idleIk\*this\.nonCombatArmOwnership\(\)\*T\.MathUtils\.clamp\(this\.weaponLayerBlend,0,1\)/.test(runtime)&&/strength\*=T\.MathUtils\.lerp\(1,\.18,moving\)/.test(runtime)&&/secondary\.combatCap/.test(runtime)&&/secondary\.idleCap/.test(runtime),'P0.26.8 support-hand contact yields during movement but can remain physically engaged for true two-hand spear/staff attacks');
pass(/jumpDuration\(\)/.test(runtime)&&/jumpAge<jumpDuration/.test(runtime)&&/Math\.sin\(jump\/jumpDuration\*Math\.PI\)/.test(runtime),'R19 Jump clip and vertical root arc share one duration');
pass(/GoldenQueen_WeaponBody_Walking/.test(queen)&&/GoldenQueen_WeaponBody_FastRun/.test(queen)&&/PLAYER_WALK_RUN_SWITCH-\.42/.test(queen)&&/blendedStride=T\.MathUtils\.lerp/.test(queen)&&/phaseHz=speed/.test(queen)&&/attackWeight\(p\)/.test(queen)&&!/const useRun=speed>=PLAYER_WALK_RUN_SWITCH/.test(queen),'R21 Golden Queen uses body-only locomotion, shared normalized gait cadence and attack-to-guard blending');
pass(!/authoritativeGlbMotionActive|syncWeaponMountsWithoutPoseEdits/.test(runtime),'obsolete all-bones GLB authority bypass is removed');
pass(/leftThumbProximal/.test(retarget)&&/rightLittleDistal/.test(retarget)&&/mixamorig:LeftHandPinky3/.test(retarget),'source retarget preserves complete humanoid limb/finger coverage under R21 normalized-bone conversion');
pass(/\['chest','mixamorig:Spine1'\]/.test(retarget)&&/\['upperChest','mixamorig:Spine2'\]/.test(retarget),'Mixamo torso remains fully mapped');
pass(/addScaledVector\(travel,-u\)/.test(retarget)&&/worldBob\.set\(0,T\.MathUtils\.clamp\(delta\.y,-\.10,\.10\),0\)/.test(retarget)&&/qinglanStrideLength/.test(retarget)&&/VectorKeyframeTrack/.test(retarget),'R21 strips root travel, preserves bounded pelvis bob and measures target-proportioned stride length');
pass(/speed:1\.7502182743728725/.test(locomotion)&&/speed:5\.545185503149063/.test(locomotion),'source GLB locomotion metadata remains measured and unchanged');
pass(/PLAYER_WALK_SPEED=3\.8/.test(locomotion)&&/PLAYER_RUN_SPEED=PLAYER_AUTHORED_LOCOMOTION\.run\.speed/.test(locomotion),'R27.2 raises normal ground travel to 3.8 m/s while keeping run speed authored');
pass(/PLAYER_RUN_SPEED:PLAYER_WALK_SPEED/.test(world)&&!/p\.input\.sprint\?7\.3:5\.2/.test(world),'server movement still uses authored locomotion speed');
pass(/applyBowDrawCorrection/.test(runtime)&&/poseCorrectionFor\(this\.activeOneShot\)/.test(runtime)&&/sampleWeaponCombatArmInto/.test(runtime)&&/kind:'bow-draw'/.test(animationProfiles)&&/leftArmCap:\.76,rightArmCap:\.88/.test(animationProfiles),'R27.2 bow draw correction remains attack-only and is now selected/bounded by motion data');
pass(/fingerStrength:\{[\s\S]*index:\.62[\s\S]*middle:\.78[\s\S]*ring:\.64[\s\S]*little:0[\s\S]*thumb:0/.test(bowDraw)&&/applyBowStringHook/.test(runtime)&&/bowDrawFingerStrength\(entry\.digit,phase,correction\)/.test(runtime),'R27.3 draw hand uses a three-finger string hook instead of a closed fist');
pass(/navLabel='追擊目標'[\s\S]*p\.input=\{x:0,z:0,sprint:true\}/.test(world),'R27.3 out-of-range queued skills pursue at Run speed while ordinary navigation remains unchanged');
pass(fs.existsSync(path.join(root,'tests/bow-pursuit-r273.test.ts')),'R27.3 bow/pursuit regression test is packaged');
pass(pkg.scripts?.['verify:r16']==='node scripts/verify-r16.mjs'&&String(pkg.scripts?.check??'').includes('verify:r16'),'existing R16 script name remains as backward-compatible release gate');
pass(gui.includes('scripts/verify-r16.mjs')&&gui.includes('R26 Verify'),'Python test center remains compatible with the R26 release gate');
const expected={
 'public/assets/animations/mixamo/Walking.glb':'dce96054f2befa04435c768ecc7c17bd22094a3b6a7013859beb773676c8ab4f',
 'public/assets/animations/mixamo/Fast_Run.glb':'00fa9f493cbd8df6cfbd170304ca199f63aba032ef575276861f93250a412b71',
};
for(const [file,hash] of Object.entries(expected))pass(sha(file)===hash,`source GLB unchanged: ${file}`);
pass(/walkStride:number=PLAYER_AUTHORED_LOCOMOTION\.walk\.rootTravel/.test(queen)&&/runStride:number=PLAYER_AUTHORED_LOCOMOTION\.run\.rootTravel/.test(queen),'R21.1 Golden Queen stride metadata remains dynamically assignable without literal-type narrowing');
pass(!/primaryAxis|idleAxisIk|combatAxisIk/.test(grip)&&/greatsword:[\s\S]*?idleIk:\.12,combatIk:\.08/.test(grip)&&/spear:[\s\S]*?combatIk:\.82[\s\S]*?combatCap:\.86/.test(grip)&&/staff:[\s\S]*?combatIk:\.76[\s\S]*?combatCap:\.80/.test(grip),'P0.26.8 removes primary wrist-axis forcing while allowing bounded strong second-hand contact for spear/staff');
pass(/ACTION_RPG_READY/.test(ready)&&/makeClipAdditive/.test(ready)&&/sourceBlend:\.32/.test(animationProfiles)&&/moveWeight:\.0[3458]/.test(animationProfiles),'R26 ready stances are clamped target-rig additive deltas derived from authored clips and almost disappear during movement');
pass(!/heavenfall-bow[^\n]*localRotation:\[0,0,-Math\.PI\/2\]/.test(curated),'R22 no longer forces the curated bow horizontal');
pass(fs.existsSync(path.join(root,'tests/weapon-stance-r22.test.ts'))&&fs.existsSync(path.join(root,'tests/weapon-layer-r24.test.ts'))&&fs.existsSync(path.join(root,'tests/weapon-style-r25.test.ts'))&&fs.existsSync(path.join(root,'tests/weapon-motion-r26.test.ts')),'R26 weapon-motion and locomotion-isolation regressions are packaged');
console.log('R26 SAFE ACTION-RPG WEAPON LAYER / AUTHORED COMBAT / BRISK WALK VERIFICATION: PASS (R16 compatibility gate)');
